# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.28.3";
    hash = "sha256-jiA/FeYEEk/u9O1gtdnOzatym+/uHyaRJSdp34TOb1o=";
  })
  (fetchNuGet {
    pname = "Grpc.Tools";
    version = "2.67.0";
    hash = "sha256-ms/lbWwb9UuJHNl3T5X2mAulCHhQ3tEiqRLWBfUYoV0=";
  })
  (fetchNuGet {
    pname = "QRCoder";
    version = "1.6.0";
    hash = "sha256-2Ev/6d7PH6K4dVYQQHlZ+ZggkCnDtrlaGygs65mDo28=";
  })
  (fetchNuGet {
    pname = "SharpZipLib";
    version = "1.4.2";
    hash = "sha256-/giVqikworG2XKqfN9uLyjUSXr35zBuZ2FX2r8X/WUY=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta4.22272.1";
    hash = "sha256-zSO+CYnMH8deBHDI9DHhCPj79Ce3GOzHCyH1/TiHxcc=";
  })
]
